### ISSUE TITLE
Can't remove tags

### ISSUE THREAD

**Issue by lukeyeager** [Stanford-IoT-Lab/thingengine-core#1]
Once I add a tag to an app, I can't remove it again.

Not sure if this belongs in this repo or in https://github.com/Stanford-IoT-Lab/thingengine-platform-cloud.

**Comment by gcampax** [comment]
(I usually track issues in ThingEngine, the old monolithic repo)

It should be possible to remove a tag by clicking on the - sign next to the tag in the edit page.

**Comment by lukeyeager** [comment]
When you click the `-` sign, the label goes away from the UI. But when you save the App, the deleted label is still there.

**Comment by gcampax** [comment]
Found the problem, fixed now

**Comment by lukeyeager** [comment]
Thanks!

**Comment by lukeyeager** [comment]
Verified fix.
